[package]
name = "kernel"
version = "0.1.0"
authors = ["Ethin Probst <harlydavidsen@gmail.com>"]
edition = "2018"

[dependencies]
x86_64 = "*"
bootloader = {version="*", features=["map_physical_memory"]}
uart_16550 = "*"
volatile = "*"
spin = "*"
pic8259_simple = "*"
pc-keyboard = "*"
raw-cpuid = "*"
cpuio = "*"
bit_field = "*"
libm = "*"
slab_allocator = "*"
rusty-asm = {version="*", features=["proc-macro"]}

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
run-args = ["-serial", "stdio", "-s", "-soundhw", "all", "-drive", "format=raw,id=disk,file=disk.img,if=none", "-device", "ahci,id=ahci", "-device", "ide-drive,drive=disk,bus=ahci.0"]
