[package]
name = "kernel"
version = "0.1.0"
authors = ["Ethin Probst <harlydavidsen@gmail.com>"]
edition = "2018"


[dependencies]
x86_64 = "*"
bootloader = {version="*", features=["map_physical_memory", "sse"]}
uart_16550 = "*"
volatile = "*"
pic8259_simple = "*"
pc-keyboard = "*"
cpuio = "*"
bit_field = "*"
slab_allocator = "*"
rusty-asm = {version="*", features=["proc-macro"]}
goblin = {version = "*", default-features=false, features=["elf64", "elf32", "mach64", "mach32", "pe32", "pe64", "archive", "endian_fd"]}
zerocopy = "0.2.8"
spin = ">= 0.5.2"

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"
opt-level=0
debug=true
rpath=false
lto=false
debug-assertions = true
codegen-units = 64
overflow-checks = true
incremental = true

[profile.release]
panic = "abort"

[package.metadata.bootimage]
run-args = ["-serial", "stdio", "-soundhw", "all", "-no-reboot", "-hdb", "disk.img", "-cpu", "max", "-s", "-m", "1G"]

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "target/sysroot"

