[package]
authors = ['Ethin Probst <harlydavidsen@gmail.com>']
build = 'build.rs'
edition = '2018'
license = 'MPL-2.0'
name = 'kernel'
version = '0.1.0'

[build-dependencies]
build_details = "0.1.2"
build_script_file_gen = "0.6.1"
rustc_version = "0.4.0"

[dependencies]
bit_field = "0.10.1"
heapless = "0.7.1"
linked_list_allocator = "0.9.0"
spin = "0.9.1"
uart_16550 = "0.2.15"
bootloader = { git = "https://github.com/rust-osdev/bootloader" }
x86_64 = "0.14.3"

[dependencies.libk]
path = 'libk'

[dependencies.log]
default-features = false
version = "0.4.14"

[package.metadata.bootloader]
kernel-stack-size = "1048576"
map-physical-memory = true
map-framebuffer = true

[profile.dev]
codegen-units = 64
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 0
overflow-checks = true
panic = 'abort'
rpath = false

[profile.release]
codegen-units = 1
lto = 'fat'
opt-level = 'z'


