[package]
authors = ['Ethin Probst <harlydavidsen@gmail.com>']
build = 'build.rs'
edition = '2018'
license = 'MPL-2.0'
name = 'kernel'
version = '0.1.0'

[package.metadata.bootloader]
kernel-stack-size = "65536"
map-physical-memory = true
map-framebuffer = true

[build-dependencies]
build_details = "0.1.2"
build_script_file_gen = "0.6.1"
rustc_version = "0.4.0"

[dependencies]
bit_field = "0.10.1"
heapless = "0.7.7"
linked_list_allocator = "0.9.0"
spin = "0.9.2"
uart_16550 = "0.2.15"
x86_64 = { version = "0.14.6", features = ["const_fn", "inline_asm", "abi_x86_interrupt", "nightly"] }
bootloader = "0.10.9"

[dependencies.libk]
path = 'libk'

[dependencies.log]
default-features = false
version = "0.4.14"

[profile.dev]
codegen-units = 2048
debug = true
debug-assertions = true
incremental = true
lto = false
opt-level = 1
overflow-checks = true
panic = 'abort'
rpath = false

[profile.release]
codegen-units = 1
lto = true
opt-level = 3


