[package]
name = "kernel"
version = "0.1.0"
authors = ["Ethin Probst <harlydavidsen@gmail.com>"]
edition = "2018"
license = "MPL-2.0"

[dependencies]
x86_64 = {git = "https://github.com/rust-osdev/x86_64", features=["deny-warnings"]}
uart_16550 = "^0.2.10"
bit_field = "^0.10.1"
spin = "^0.7.0"
heapless = "^0.5.6"
bootloader = {version = "^0.9.11", features=["map_physical_memory", "sse"]}
linked_list_allocator = "^0.8.6"
log = {version = "^0.4.11", default-features=false}
libk = {path = "libk"}
vga = "^0.2.5"

[dependencies.lazy_static]
version = ">=1.4.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"
opt-level=0
debug=true
rpath=false
lto=false
debug-assertions = true
codegen-units = 64
overflow-checks = true
incremental = true

[profile.release]
panic = "abort"
lto = "thin"
codegen-units = 1

[package.metadata.bootimage]
run-args = ["-no-reboot", "-drive", "file=disk.img,if=none,id=NVME01", "-device", "nvme,drive=NVME01,serial=0001", "-m", "4G", "-usb", "-rtc", "base=utc,clock=host", "-cpu", "Skylake-Client-v3", "-smp", "cpus=8", "-M", "q35", "-name", "kernel", "-s", "-nographic", "-d", "trace:pci_nvme_*", "-D", "qemu.log"]

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "target/sysroot"

[package.metadata.bootloader]
kernel-stack-size = 2048

