[package]
name = "kernel"
version = "0.1.0"
authors = ["Ethin Probst <harlydavidsen@gmail.com>"]
edition = "2018"


[dependencies]
x86_64 = ">=0.9.6"
uart_16550 = ">=0.2.4"
volatile = ">=0.2.6"
pc-keyboard = ">=0.5.0"
cpuio = ">=0.2.0"
bit_field = ">=0.10.0"
goblin = {version = ">=0.2.0", default-features=false, features=["elf64", "elf32", "mach64", "mach32", "pe32", "pe64", "archive", "endian_fd"]}
spin = ">= 0.5.2"
raw-cpuid = ">=7.0.3"
part = {path = "drivers/storage/part"}
heapless = "0.5.5"
anyhow = {version = "1.0.31", default-features=false}
bootloader = {version = "0.9.4", features=["map_physical_memory", "sse"]}
rand = {version = "0.7.3", default-features=false, features = ["alloc"]}
bitflags = "1.2.1"
atomic = "0.4.5"
acpi = "1.0.0"
buddy_system_allocator = "0.4.0"

[dependencies.lazy_static]
version = ">=1.4.0"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"
opt-level=0
debug=true
rpath=false
lto=false
debug-assertions = true
codegen-units = 64
overflow-checks = true
incremental = true

[profile.release]
panic = "abort"
lto = "fat"
codegen-units = 1

[package.metadata.bootimage]
run-args = ["-serial", "stdio", "-no-reboot", "-hdb", "disk.img", "-s", "-m", "4G", "-usb", "-rtc", "base=utc,clock=host", "-cpu", "EPYC-v3,+apic,+acpi", "-smp", "cpus=8", "-soundhw", "all", "-M", "q35"]

[package.metadata.cargo-xbuild]
memcpy = true
sysroot_path = "target/sysroot"

