[package]
name = "kernel"
version = "0.1.0"
authors = ["Ethin Probst <harlydavidsen@gmail.com>"]
edition = "2018"

[dependencies]
x86_64 = "*"
bootloader = {version="*", features=["map_physical_memory"]}
uart_16550 = "*"
volatile = "*"
spin = "*"
pic8259_simple = "*"
pc-keyboard = "*"
cpuio = "*"
bit_field = "*"
slab_allocator = "*"
rusty-asm = {version="*", features=["proc-macro"]}
goblin = {version = "*", default-features=false, features=["elf64", "elf32", "mach64", "mach32", "pe32", "pe64", "archive", "endian_fd"]}
cty = "0.2.0"

[dependencies.lazy_static]
version = "*"
features = ["spin_no_std"]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[package.metadata.bootimage]
run-args = ["-serial", "stdio", "-soundhw", "all", "-no-reboot", "-cpu", "max", "-drive", "format=raw,id=disk,file=disk.img,if=none", "-device", "ich9-ahci,id=ahci", "-device", "ide-drive,drive=disk,bus=ahci.0"]
