[package]
name = "part"
version = "0.1.0"
authors = ["Ethin Probst <harlydavidsen@gmail.com>"]
edition = "2018"

[dependencies]
heapless = "0.5.5"
zerocopy = "0.3.0"
static_assertions = "1.1.0"
anyhow = {version = "1.0.31", default-features=false}
uuid = {version = "0.8.1", default-features=false}
