[package]
name = "libk"
version = "0.1.0"
authors = ["Ethin Probst <ethindp@protonmail.com>"]
edition = "2018"

[dependencies]
x86_64 = {git = "https://github.com/rust-osdev/x86_64", features=["deny-warnings"]}
cpuio = "^0.3.0"
bit_field = "^0.10.0"
spin = "^0.7.0"
raw-cpuid = "^8.1.2"
heapless = "^0.5.6"
acpi = "^2.0.0"
bootloader = {version = "^0.9.11", features=["map_physical_memory", "sse"]}
x86 = "^0.34.0"
iced-x86 = {version = "^1.9.1", default-features=false, features=["decoder", "encoder", "block_encoder", "op_code_info", "instr_info", "gas", "intel", "masm", "nasm", "db", "no_std", "exhaustive_enums"]}
linked_list_allocator = "^0.8.6"
voladdress = {git = "https://github.com/rust-console/voladdress"}
bitflags = "^1.2.1"
crossbeam-queue = {version = "^0.3.1", default-features=false, features=["alloc"]}
log = {version = "^0.4.11", default-features=false}
byteorder = {version = "^1.3.4", default-features=false}
block_device = "^0.1.2"
dia-semver = "^8.0.1"
zerocopy = "^0.3.0"
static_assertions = "^1.1.0"
minivec = "^0.1.3"

[dependencies.lazy_static]
version = "^1.4.0"
features = ["spin_no_std"]
