[dependencies]
acpi = "2.2.0"
bit_field = "0.10.1"
bitflags = "1.2.1"
block_device = "0.1.2"
cpuio = "0.3.0"
dia-semver = "8.0.1"
heapless = "0.5.6"
linked_list_allocator = "0.8.11"
minivec = "0.2.0"
rand_hc = "0.3.0"
raw-cpuid = "9.0.0"
spin = "0.7.1"
static_assertions = "1.1.0"
x86 = "0.35.0"
zerocopy = "0.3.0"
bitintr = "0.3.0"

[dependencies.bootloader]
features = [
    'map_physical_memory',
    'sse',
]
version = "0.9.11"

[dependencies.byteorder]
default-features = false
version = "1.4.2"

[dependencies.crossbeam-queue]
default-features = false
features = ['alloc']
version = "0.3.1"

[dependencies.hashbrown]
default-features = false
features = [
    'nightly',
    'inline-more',
    'ahash',
    'ahash-compile-time-rng',
]
version = "0.9.1"

[dependencies.iced-x86]
default-features = false
features = [
    'decoder',
    'encoder',
    'block_encoder',
    'op_code_info',
    'instr_info',
    'gas',
    'intel',
    'masm',
    'nasm',
    'db',
    'no_std',
    'exhaustive_enums',
]
version = "1.10.0"

[dependencies.lazy_static]
features = ['spin_no_std']
version = "1.4.0"

[dependencies.log]
default-features = false
version = "0.4.13"

[dependencies.rand_core]
default-features = false
features = ['alloc']
version = "0.6.1"

[dependencies.voladdress]
git = 'https://github.com/rust-console/voladdress'

[dependencies.x86_64]
git = 'https://github.com/rust-osdev/x86_64'

[features]
default = ['nvme']
nvme = []

[package]
authors = ['Ethin Probst <ethindp@protonmail.com>']
edition = '2018'
name = 'libk'
version = '0.1.0'
